In [2]:
import pandas as pd
import numpy as np
import json

In [3]:
import json
with open('../data/raw/orders.json') as f:orders=json.load(f)
jdf=pd.json_normalize(orders)
jdf.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI

In [4]:
print(jdf.dtypes)

order_id            object
restaurant_name     object
order_date          object
order_value        float64
discount_used       object
payment_method      object
dtype: object

In [6]:
jdf['order_date']=pd.to_datetime(jdf['order_date'])
jdf['year']=jdf['order_date'].dt.year
jdf['month']=jdf['order_date'].dt.month
jdf['month_name']=jdf['order_date'].dt.month_name()
jdf.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method,year,month,month_name
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card,2025,5,May
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash,2026,1,January
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI,2026,1,January
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI,2025,11,November
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI,2025,12,December

In [7]:
print(jdf['discount_used'].unique())

['No' 'Yes']

In [8]:
print(jdf['payment_method'].unique())

['Card' 'Cash' 'UPI']

In [9]:
print(jdf['year'].unique())
print(jdf['month'].unique())
print(jdf['month_name'].unique())

[2025 2026]
[ 5  1 11 12  9  7 10  8  6  2  4]
['May' 'January' 'November' 'December' 'September' 'July' 'October'
 'August' 'June' 'February' 'April']

In [11]:
print(jdf.isnull().sum())

order_id           0
restaurant_name    0
order_date         0
order_value        0
discount_used      0
payment_method     0
year               0
month              0
month_name         0
dtype: int64

In [12]:
print(jdf.duplicated().sum())

0

In [15]:
print(jdf.dtypes)

order_id                   object
restaurant_name            object
order_date         datetime64[ns]
order_value               float64
discount_used              object
payment_method             object
year                        int32
month                       int32
month_name                 object
dtype: object

In [18]:
import os
os.makedirs('../data/clean',exist_ok=True)
jdf.to_csv('../data/clean/jsonorders_clean.csv', index=False)
print('save successfuly')
print(f"Rows:{len(jdf)}")

save successfuly
Rows:25000